# Generated by Django 4.0.4 on 2022-06-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accounts_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='otp',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
