# Generated by Django 4.0.4 on 2022-06-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accounts_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
