# Generated by Django 4.0.4 on 2022-06-12 09:23

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_accounts_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
