# Generated by Django 4.0.4 on 2022-08-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_accounts_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='is_landlord',
            field=models.BooleanField(default=False),
        ),
    ]
