# Generated by Django 4.0.4 on 2022-08-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_accounts_is_landlord'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='picture',
            field=models.ImageField(null=True, upload_to='Landlords'),
        ),
    ]
