# Generated by Django 4.0.4 on 2022-11-15 20:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wifi', models.BooleanField(default=False)),
                ('water', models.BooleanField(default=False)),
                ('dirt_collection', models.BooleanField(default=False)),
                ('gymn', models.BooleanField(default=False)),
                ('food', models.BooleanField(default=False)),
                ('brddings', models.BooleanField(default=False)),
                ('transport', models.BooleanField(default=False)),
                ('entertainment', models.BooleanField(default=False)),
                ('security', models.BooleanField(default=False)),
                ('laundry', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('category', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('lon', models.DecimalField(decimal_places=7, default=0, max_digits=10, null=True)),
                ('lat', models.DecimalField(decimal_places=7, default=0, max_digits=10, null=True)),
                ('rooms_available', models.IntegerField(default=0)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hostel_name', models.CharField(max_length=150, unique=True)),
                ('hostel_description', models.CharField(max_length=1000)),
                ('hostel_rating', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5, 'Should be less than 5'), django.core.validators.MinValueValidator(1, 'Should be more than 0')])),
                ('lefla_for_rental_collection', models.BooleanField(default=False)),
                ('hostel', models.BooleanField(default=False)),
                ('avilable_amenities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostels.amenities')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=250, primary_key=True, serialize=False)),
                ('pricing', models.FloatField()),
                ('offer', models.FloatField()),
                ('deposit', models.IntegerField()),
                ('service_fee', models.IntegerField()),
                ('number_of_rooms_avilable', models.IntegerField(default=0)),
                ('hostel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostels.hostel', verbose_name='hostel-room')),
                ('room_type', models.ForeignKey(default='Other', null=True, on_delete=django.db.models.deletion.CASCADE, to='hostels.categorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('Transaction_id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('amount', models.FloatField()),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_number', models.CharField(max_length=15)),
                ('receiver_number', models.CharField(max_length=15)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Virtual_Wallet',
            fields=[
                ('available_amount', models.FloatField(default=0)),
                ('wallet_id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('amount_owed', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomImages',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('image_url_1', models.ImageField(upload_to='hostel_images')),
                ('image_url_2', models.ImageField(upload_to='hostel_images')),
                ('image_url_3', models.ImageField(upload_to='hostel_images')),
                ('image_url_4', models.ImageField(upload_to='hostel_images')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostels.room')),
            ],
        ),
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hostel',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostels.landlord'),
        ),
    ]
