# Generated by Django 4.0.4 on 2022-11-15 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0008_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryModel',
            new_name='Category',
        ),
    ]
