# Generated by Django 4.0.4 on 2022-11-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0009_rename_categorymodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='place_name',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='hostel',
            name='town',
            field=models.CharField(default='', max_length=70),
        ),
    ]
