# Generated by Django 4.0.4 on 2022-11-15 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0010_hostel_place_name_hostel_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='hostel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostels.hostel', verbose_name='hostel'),
        ),
    ]
