# Generated by Django 4.0.4 on 2022-11-15 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0011_alter_room_hostel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='checker',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='roomimages',
            name='room_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hostels.room'),
        ),
    ]
