# Generated by Django 4.0.4 on 2022-11-16 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0012_room_checker_alter_roomimages_room_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='checker',
        ),
    ]
