# Generated by Django 4.0.4 on 2023-01-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0014_rename_receiver_number_transactions_receiver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='rooms_available',
        ),
        migrations.RemoveField(
            model_name='room',
            name='number_of_rooms_avilable',
        ),
        migrations.AddField(
            model_name='room',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
    ]
