# Generated by Django 4.0.4 on 2022-11-19 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('Transactions', '0002_unconfirmedmpesastkpush'),
    ]

    operations = [
        migrations.AddField(
            model_name='unconfirmedmpesastkpush',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bookings.bookings'),
        ),
        migrations.AlterField(
            model_name='unconfirmedmpesastkpush',
            name='status',
            field=models.CharField(choices=[('PAID', 'PAID'), ('CANCELLED', 'CANCELLED'), ('ERROR', 'ERROR'), ('IN_PROGRESS', 'IN_PROGRES')], default='IN_PROGRESS', max_length=100),
        ),
    ]
