# Generated by Django 4.0.4 on 2022-11-16 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostels', '0013_remove_room_checker'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_id', models.CharField(default=uuid.uuid4, max_length=130, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('REQUESTED', 'REQUESTED'), ('ACCEPTED', 'ACCEPTED'), ('BOOKED', 'BOOKED'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], default='REQUESTED', max_length=50)),
                ('reason_for_cancelling', models.CharField(blank=True, max_length=800, null=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostels.hostel')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
            },
        ),
        migrations.CreateModel(
            name='DamagePenalty',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('penalty_id', models.CharField(default=uuid.uuid4, max_length=130, primary_key=True, serialize=False)),
                ('item_damaged', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=600)),
                ('amount_charged', models.FloatField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkout_id', models.CharField(default=uuid.uuid4, max_length=130, primary_key=True, serialize=False)),
                ('amount_paid', models.FloatField(default=0)),
                ('is_paid', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bookings.bookings')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
