# Generated by Django 4.0.4 on 2022-11-19 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0013_remove_room_checker'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='hostel',
        ),
        migrations.AddField(
            model_name='bookings',
            name='room',
            field=models.ForeignKey(default='9305ec4b-8a23-49bf-a2e7-d3d8479bd793', on_delete=django.db.models.deletion.CASCADE, to='hostels.room'),
        ),
    ]
