# Generated by Django 4.0.4 on 2022-11-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_bookings_hostel_bookings_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'REQUESTED'), ('ACCEPTED', 'ACCEPTED'), ('VISITED', 'VISITED'), ('BOOKED', 'BOOKED'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], default='REQUESTED', max_length=50),
        ),
    ]
